[build]
  command = "npm install && npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "22.19.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERBOSE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PRIVATE_TARGET = "server"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  
# Configure build plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@supabase/supabase-js",
    "@supabase/auth-helpers-nextjs",
    "@supabase/ssr",
    "@radix-ui/*",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "framer-motion",
    "lucide-react"
  ]
  included_files = [
    ".netlify/functions-include.js"
  ]
  directory = ".next/server/pages"

# Disable Edge Functions as we're using Next.js middleware
[dev]
  framework = "next"