[build]
  command = "npm install && npm run build"
  publish = ".next"
  
[build.environment]
  NODE_VERSION = "22.19.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERBOSE = "true"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NEXT_PRIVATE_TARGET = "server"
  
# Configure build plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    buildCommand = "npm run build"
    publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@supabase/functions-js", 
    "@supabase/supabase-js",
    "@supabase/auth-helpers-nextjs",
    "@supabase/ssr",
    "@radix-ui/*",
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "framer-motion",
    "lucide-react"
  ]
  included_files = [
    ".netlify/functions-include.js"
  ]
  directory = ".next/server/pages"

# Enable Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  package = "@netlify/plugin-nextjs"
  # The plugin handles Next.js configuration automatically
  # No custom inputs are needed as they're not supported by this plugin

# Disable Edge Functions as we're using Next.js middleware
[dev]
  framework = "next"